apiVersion: v1

kind: Pod

metadata:
  name: my-pod
  labels: 
    app: mohamed

spec:
  containers:
  - name: my-container
    image: mohamed2esmael/python-docker
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
